fix: alteração na estrutura do exercício 1, e correção do exercício 1, letra b
julianapedroso/HelpperOrigins-sprint01 pull request #1
Opened 2021-10-28 23:37 UTC by julianapedroso

- fix: alteração na estrutura do exercício 1, e correção do exercício 1, letra b

2021-10-28 23:39 UTC, julianapedroso commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 1](https://trello.com/c/xDPl92S6/28-exerc%C3%ADcio-1)

2021-10-29 01:01 UTC, julianapedroso commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 1](https://trello.com/c/xDPl92S6/28-exerc%C3%ADcio-1)

2021-10-29 11:08 UTC, ErickSasaki requested changes

2021-10-29 11:08 UTC, ErickSasaki commented on exercicio2.js
> +"use strict";
Acredito que isso não era pra estar aqui, tomar cuidado com os arquivos que está commitando, evitar usar "git add ." antes de commitar caso seja o caso.

2021-10-29 11:08 UTC, ErickSasaki commented on exercicio1b/exercicio1b.ts
> +    const text: HTMLSelectElement = document.getElementById("input") as HTMLSelectElement;
Esse nome pode melhorar, text está estranho visto que ele é um input (poderia ficar inputText ou algo do tipo), a tipagem está errada também, nesse caso seria HTMLInputElement.

2021-10-29 11:08 UTC, ErickSasaki commented on exercicio1b/exercicio1b.ts
> +const getInputValue = (event: Event) => {
Faltou tipar o retorno da função, nesse caso como não retorna nada deve tipar como void.

2021-10-29 11:08 UTC, ErickSasaki commented on exercicio1b/exercicio1b.ts
> +const vowelsCountInput = (word: string) => {
Não havia reparado na 1 review, mas faltou tipar o retorno da função

2021-10-29 11:08 UTC, ErickSasaki commented on exercicio1b/exercicio1b.ts
> +    let totalVowels = 0;
Não havia reparado na 1 review, faltou tipar "totalVowels"

2021-10-29 21:02 UTC, ErickSasaki approved these changes

2021-10-30 15:38 UTC, merged