fix: correção da função que contabiliza a quantidade de vogais da palavra recebida
julianapedroso/HelpperOrigins-sprint01 pull request #3
Opened 2021-11-07 19:43 UTC by julianapedroso

- fix: correção da função que contabiliza a quantidade de vogais da palavra recebida

2021-11-07 19:44 UTC, julianapedroso commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercício 1](https://trello.com/c/xDPl92S6/28-exerc%C3%ADcio-1)

2021-11-08 21:31 UTC, matheus-yudi-helpper requested changes

2021-11-08 21:31 UTC, matheus-yudi-helpper commented on exercicio1a/exercicio1a.ts
> +    const vowels: string = '/[^aeiou]/gi';
Dessa forma que está você precisaria aplicar uma RegExp para validar a existência das vogais. Você pode apenas usar uma string contínua: `const vowels: string = 'aeiou'` que é mais simples.

2021-11-08 21:31 UTC, matheus-yudi-helpper commented on exercicio1b/exercicio1b.ts
> +    const vowels: string = '/[^aeiou]/gi';
Dessa forma que está você precisaria aplicar uma RegExp para validar a existência das vogais. Você pode apenas usar uma string contínua: `const vowels: string = 'aeiou'` que é mais simples.

2021-11-08 22:28 UTC, julianapedroso commented on exercicio1a/exercicio1a.ts
> +    const vowels: string = '/[^aeiou]/gi';
acabei mudando o loop e deixando a string 'aeiou' como sugeriu :)

2021-11-08 22:52 UTC, matheus-yudi-helpper approved these changes

2021-11-08 23:35 UTC, merged